name: Build NetPing Dylib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos và SDK
        run: |
          # Cài Theos
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # Tải SDK iPhone để sửa lỗi 'could not build module'
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          # Tạo file giả nếu thiếu để tránh lỗi file not found
          touch x2nios.h
          # Lệnh build ép dùng SDK đã tải
          make FINALPACKAGE=1 ARCHS="arm64 arm64e" SDKVERSION=14.5
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: NetPing-Dylib
          path: .theos/obj/*.dylib
