name: Build NetPing Dylib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Tải cả các thư viện đi kèm

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          # Lệnh làm sạch bản build cũ trước khi build mới
          make clean
          make FINALPACKAGE=1 ARCHS="arm64 arm64e"
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: NetPing-Dylib
          path: .theos/obj/*.dylib
