name: Build LGL Menu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone https://github.com/theos/theos.git ~/theos
          mkdir -p ~/theos/sdks
          # Lấy SDK iPhone có sẵn trong máy ảo GitHub để tránh lỗi module
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk ~/theos/sdks/iPhoneOS.sdk
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make FINALPACKAGE=1 ARCHS="arm64 arm64e"
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: LGL-Menu-Dylib
          path: .theos/obj/*.dylib
